--- 
cache: 
  directories: 
    - ~/.npm
deploy: 
  commit_message: "Deploy Release"
  edge: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  true: 
    branch: master
git: 
  depth : 3
language : node_js
node_js : - "10"
script : 
  - "yarn build"
